/* 00-data.js
   DATA: certifications, badges, titles
   Part of Claude Cert Quest. Loaded as a classic script: every file
   shares one global scope, in the order listed in index.html. */
"use strict";
/* ================= DATA ================= */
const CERTS = [
 {id:"ccao", code:"CCAO-F", name:"Claude Certified Associate", sub:"Foundations", price:"$99", em:"🎯", color:"#5a9e6f",
  blurb:"For consultants, sellers, and delivery leads who guide customers toward the right Claude use cases.",
  domains:["Prompting","Output Evaluation","Model Selection","Workflow Integration","Knowledge Management","Governance & Risk","Troubleshooting"],
  questions:[], cards:[]},
 {id:"ccdv", code:"CCDV-F", name:"Claude Certified Developer", sub:"Foundations", price:"$125", em:"🛠️", color:"#5b7fa6",
  blurb:"For engineers who build with the Claude API, Claude Code, and Model Context Protocol.",
  domains:["API Mechanics","Tool Use & Structured Output","Agents & SDK","Model Selection & Cost","Prompt & Context Engineering","Security","MCP"],
  questions:[], cards:[]},
 {id:"ccaf", code:"CCAR-F", name:"Claude Certified Architect", sub:"Foundations", price:"$125", em:"🏛️", color:"#d97757",
  blurb:"For partners who design Claude solutions end to end — deployment platforms and agentic architectures.",
  domains:["Agentic Architecture & Orchestration","Claude Code Workflows","Prompt Engineering & Structured Output","Tool Design & MCP Integration","Context Management & Reliability"],
  questions:[], cards:[]},
 {id:"ccap", code:"CCAR-P", name:"Claude Certified Architect", sub:"Professional", price:"$175", em:"👑", color:"#8a6fae",
  blurb:"Advanced, scenario-driven agentic system design at production scale.",
  domains:["Multi-Agent Systems at Scale","Reliability & Error Recovery","Cost, Latency & Model Strategy","Evaluation & Observability","Security & Governance of Agents"],
  questions:[], cards:[]}
];

const BADGES = [
 {id:"mind_mapper", em:"🧠", name:"Mind Mapper", desc:"Explore conceptual mind maps mapping Claude architecture relationships"},
 {id:"inline_sandbox_master", em:"🧪", name:"Inline Sandbox Master", desc:"Edit live XML tags in embedded lesson playgrounds"},
 {id:"audio_recap_scholar", em:"📖", name:"Audio Recap Scholar", desc:"Listen to 30-second high-yield lesson audio recaps"},
 {id:"whatif_explorer", em:"❓", name:"What-If Explorer", desc:"Explore edge-case Socratic scenario trees in study lessons"},
 {id:"sequence_diagrammer", em:"📊", name:"Sequence Diagrammer", desc:"Interact with animated architecture sequence flows in study guide lessons"},
 {id:"socratic_scholar", em:"💡", name:"Socratic Scholar", desc:"Complete Socratic conceptual probes at the end of lessons"},
 {id:"sdk_annotator", em:"🔍", name:"SDK Annotator", desc:"Inspect annotated Python & TypeScript SDK code walkthroughs"},
 {id:"lecture_listener", em:"🎙️", name:"Lecture Listener", desc:"Listen to synchronized audio lectures with transcript autoscroll"},
 {id:"microvm_guard", em:"🔒", name:"MicroVM Guard", desc:"Simulate Zero-Trust MicroVM tool execution sandboxes"},
 {id:"consensus_judge", em:"⚖️", name:"Consensus Judge", desc:"Evaluate multi-model majority voting & LLM-as-a-Judge setups"},
 {id:"cache_warming_specialist", em:"⏱️", name:"Cache Warming Specialist", desc:"Simulate 5-minute prompt caching TTL renewal & prefix warming"},
 {id:"speed_audio_specialist", em:"🎙️", name:"Speed Audio Specialist", desc:"Complete 10-second rapid voice answer challenges"},
 {id:"cli_engineer", em:"💻", name:"CLI Engineer", desc:"Execute simulated Claude Code CLI terminal commands"},
 {id:"rate_limit_specialist", em:"⚡", name:"Rate Limit Specialist", desc:"Simulate Anthropic API rate limits and token bucket refill loops"},
 {id:"deck_builder", em:"📊", name:"Deck Builder", desc:"Build and export custom flashcard CSV study decks"},
 {id:"vector_badge_master", em:"🏆", name:"Vector Badge Master", desc:"Export high-resolution cryptographic SVG vector badges"},
 {id:"whiteboard_duelist", em:"⚔️", name:"Whiteboard Duelist", desc:"Complete a 3-minute P2P real-time architecture whiteboard duel"},
 {id:"prompt_optimizer", em:"🧪", name:"Prompt Optimizer", desc:"Refactor raw prompts into XML-structured positive framing"},
 {id:"pareto_pioneer", em:"📈", name:"Pareto Pioneer", desc:"Analyze P99 latency vs cost trade-offs on the Pareto frontier"},
 {id:"podcast_producer", em:"🎙️", name:"Podcast Producer", desc:"Stream continuous hands-free audio flashcard podcast briefings"},
 {id:"digital_credentialist", em:"🏆", name:"Digital Credentialist", desc:"Generate OpenBadge v2.0 verification metadata and LinkedIn card"},
 {id:"dag_orchestrator", em:"🧩", name:"DAG Orchestrator", desc:"Build and validate multi-agent DAG topologies with SDK export"},
 {id:"red_team_defender", em:"⚡", name:"Red Team Defender", desc:"Defend against indirect prompt injection and tool hijacking attacks"},
 {id:"dossier_analyst", em:"📊", name:"Dossier Analyst", desc:"Generate comprehensive diagnostic readiness scorecard PDF report"},
 {id:"hybrid_architect", em:"📊", name:"Hybrid Reasoning Architect", desc:"Compare adaptive thinking and effort levels against Haiku-tier tradeoffs"},
 {id:"compaction_wizard", em:"🧩", name:"Compaction Wizard", desc:"Simulate multi-turn rolling state context compaction"},
 {id:"finops_master", em:"⚡", name:"FinOps Master", desc:"Calculate real-time API bills with thinking budget token profiler"},
 {id:"board_certified", em:"🎙️", name:"Board Certified Architect", desc:"Pass the multi-persona executive architectural defense board"},
 {id:"memory_master", em:"📉", name:"Memory Master", desc:"Simulate Ebbinghaus forgetting curve retention decay"},
 {id:"cache_optimizer", em:"⚡", name:"Cache Optimizer", desc:"Debug and resolve prompt caching breakpoint invalidations"},
 {id:"blitz_champion", em:"🎮", name:"Blitz Champion", desc:"Complete a 60-second rapid flashcard blitz session"},
 {id:"custom_crammer", em:"🖨️", name:"Custom Crammer", desc:"Generate and print a personalized single-page exam cram sheet"},
 {id:"calibrated_mind", em:"📊", name:"Calibrated Mind", desc:"Compute Brier confidence score to eliminate overconfidence"},
 {id:"mcp_master_builder", em:"🔌", name:"MCP Master Builder", desc:"Execute mock MCP tool invocations in the live simulator"},
 {id:"cohort_leader", em:"👥", name:"Cohort Leader", desc:"Join or create a private study group cohort"},
 {id:"aesthetic_alchemist", em:"🎨", name:"Aesthetic Alchemist", desc:"Customize study theme palette in the Theme Studio"},
 {id:"pacing_strategist", em:"⏱️", name:"Pacing Strategist", desc:"Set exam countdown and generate personalized daily pacing plan"},
 {id:"topology_architect", em:"🧩", name:"Topology Architect", desc:"Assemble and validate an enterprise Claude system topology"},
 {id:"disciplined_scholar", em:"🔔", name:"Disciplined Scholar", desc:"Enable study reminders and flashcard notification alerts"},
 {id:"audio_annotator", em:"🎙️", name:"Audio Annotator", desc:"Record and playback spoken voice notes on study lessons"},
 {id:"voice_commuter", em:"🎧", name:"Voice Commuter", desc:"Complete a hands-free voice-activated commuter quiz"},
 {id:"heatmap_master", em:"📊", name:"Heatmap Master", desc:"Inspect candidate 400-question mastery heatmap"},
 {id:"daily_slayer", em:"🏆", name:"Daily Slayer", desc:"Defeat the rotating 24-hour Daily Boss challenge"},
 {id:"crypto_verified", em:"📄", name:"Crypto Verified", desc:"Generate a cryptographic SHA-256 verifiable diploma"},
 {id:"arcade_legend", em:"🎮", name:"Arcade Legend", desc:"Survive 10+ rounds in the Arcade Survival Gauntlet"},
 {id:"socratic_scholar", em:"💬", name:"Socratic Scholar", desc:"Engage in a Socratic AI tutoring session"},
 {id:"anki_grandmaster", em:"📦", name:"Anki Grandmaster", desc:"Export an Anki-compatible study deck"},
 {id:"community_titan", em:"🌐", name:"Community Titan", desc:"Inspect the global community leaderboard"},
 {id:"candidate_identity", em:"👤", name:"Identity Verified", desc:"Customize and verify candidate callsign and avatar"},
 {id:"arena_champion", em:"👥", name:"Arena Champion", desc:"Compete in a real-time peer quiz battle"},
 {id:"blueprint_architect", em:"🧩", name:"Blueprint Architect", desc:"Construct and launch a custom exam blueprint"},
 {id:"statistical_master", em:"📊", name:"Statistical Master", desc:"Inspect mathematical pass probability confidence intervals"},
 {id:"mobile_pioneer", em:"📱", name:"Mobile Pioneer", desc:"Export native mobile Capacitor configuration"},
 {id:"pacing_virtuoso", em:"⏱️", name:"Pacing Virtuoso", desc:"Master strict 90-second per-question exam pacing"},
 {id:"voice_virtuoso", em:"🎙️", name:"Voice Virtuoso", desc:"Practice active voice recognition recall on flashcards"},
 {id:"quad_cert_master", em:"📈", name:"Quad-Cert Master", desc:"View the 4-track multi-cert mastery overlay radar"},
 {id:"offline_sovereign", em:"📦", name:"Offline Sovereign", desc:"Download the self-contained standalone offline bundle"},
 {id:"pace_master", em:"🏆", name:"Pace Master", desc:"Log a sub-3 second response time in Speed Run"},
 {id:"forecast_planner", em:"📅", name:"Master Planner", desc:"Inspect 14-day spaced repetition card maturity in the forecast matrix"},
 {id:"social_certified", em:"🎓", name:"Social Certified", desc:"Generate a shareable verification badge card"},
 {id:"benchmarking_pro", em:"🧪", name:"Benchmark Pro", desc:"Run comparative prompt regression tests in the benchmark lab"},
 {id:"cloud_sync", em:"☁️", name:"Cloud Synchronizer", desc:"Sync progress across devices via private GitHub Gist"},
 {id:"daily_achiever", em:"🎯", name:"Daily Achiever", desc:"Complete all 3 daily study targets"},
 {id:"executive_dossier", em:"📄", name:"Executive Dossier", desc:"Generate the official candidate portfolio dossier"},
 {id:"polyglot_scholar", em:"🌐", name:"Polyglot Scholar", desc:"Switch study interface language"},
 {id:"trap_hunter", em:"⚡", name:"Trap Hunter", desc:"Spot critical exam code traps in the Trap Hunter mini-game"},
 {id:"audio_scholar", em:"🎙️", name:"Audio Scholar", desc:"Complete a hands-free Audio Quiz session"},
 {id:"reasoning_master", em:"🧠", name:"Reasoning Master", desc:"Explore Extended Thinking token allocation in the trace visualizer"},
 {id:"top_percentile", em:"📊", name:"Elite Candidate", desc:"Reach the top 10% benchmark curve in Global Readiness"},
 {id:"mock_interview", em:"🎙️", name:"Board Certified", desc:"Clear the Anthropic Oral Defense Review Board"},
 {id:"roi_architect", em:"💰", name:"FinOps Master", desc:"Calculate production cost ROI in the Model Calculator"},
 {id:"context_master", em:"🧱", name:"Token Tactician", desc:"Simulate 80% semantic context compaction"},
 {id:"flash_match", em:"⚡", name:"Lightning Recall", desc:"Complete Flash Recall Speed Match in under 45 seconds"},
 {id:"war_room", em:"🏛️", name:"War Room Master", desc:"Successfully clear an enterprise architecture challenge"},
 {id:"prompt_master", em:"🧪", name:"Golden Prompter", desc:"Achieve a 95%+ score in Golden Prompt Studio"},
 {id:"mcp_engineer", em:"🔌", name:"Protocol Pioneer", desc:"Simulate full MCP tool-use lifecycle in the workbench"},
 {id:"boss_slayer", em:"⚔️", name:"Boss Battle Victor", desc:"Conquer an adaptive 25-question final Boss Battle"},
 {id:"first", em:"🌱", name:"First Steps", desc:"Answer your first question"},
 {id:"combo5", em:"🔥", name:"On Fire", desc:"5 correct in a row"},
 {id:"combo10", em:"⚡", name:"Unstoppable", desc:"10 correct in a row"},
 {id:"lvl3", em:"📈", name:"Climber", desc:"Reach level 3"},
 {id:"lvl6", em:"🚀", name:"Ascendant", desc:"Reach level 6"},
 {id:"cards25", em:"🃏", name:"Card Shark", desc:"Review 25 flashcards"},
 {id:"mock1", em:"⏱️", name:"Dress Rehearsal", desc:"Finish a mock exam"},
 {id:"pass_ccao", em:"🎯", name:"Associate Ace", desc:"Pass a CCAO-F mock (720+)"},
 {id:"pass_ccdv", em:"🛠️", name:"Developer Dynamo", desc:"Pass a CCDV-F mock (720+)"},
 {id:"pass_ccaf", em:"🏛️", name:"Architect Apprentice", desc:"Pass a CCAR-F mock (720+)"},
 {id:"pass_ccap", em:"👑", name:"Grand Architect", desc:"Pass a CCAR-P mock (720+)"},
 {id:"allseen", em:"🗺️", name:"Cartographer", desc:"Try every certification"},
 {id:"perfect10", em:"💎", name:"Flawless", desc:"Perfect 10-question quiz round"},
 {id:"streak3", em:"📅", name:"Habit Forming", desc:"3-day study streak"},
 {id:"scholar_ccao", em:"📘", name:"Associate Scholar", desc:"Read every CCAO-F lesson"},
 {id:"scholar_ccdv", em:"📗", name:"Developer Scholar", desc:"Read every CCDV-F lesson"},
 {id:"scholar_ccaf", em:"📙", name:"Architect Scholar", desc:"Read every CCAR-F lesson"},
 {id:"scholar_ccap", em:"📕", name:"Master Scholar", desc:"Read every CCAR-P lesson"},
 {id:"polymath", em:"🎓", name:"Polymath", desc:"Complete the study guide for all 4 certifications"}
];

const TITLES = ["Curious Newcomer","Prompt Novice","Context Wrangler","Token Tactician","Workflow Wizard","Agent Whisperer","MCP Maestro","Orchestration Oracle","Claude Sage","Certification Legend"];
